version: '3'
services:
  server:
    image: server
    build:
      dockerfile: Dockerfile
      context: server
    ports:
      - 5000:5000
  client:
    image: client
    build:
      dockerfile: Dockerfile
      context: client